
"""Auto-generated from schemas/bronze/bronze-ismr-occurrences-v1.yaml.

DO NOT EDIT BY HAND. Regenerate via ``tools/codegen/generate_pydantic.py``.

Contract: bronze-ismr-occurrences
Version:  1.0.0
Entity:   bronze_ismr_occurrences
"""

from __future__ import annotations

from datetime import date, datetime
from typing import Optional

from pydantic import BaseModel, ConfigDict, Field


class BronzeIsmrOccurrencesRow(BaseModel):
    """Row model for ``bronze_ismr_occurrences`` (bronze layer)."""

    model_config = ConfigDict(extra="forbid", populate_by_name=True)

category: str = Field(
        ...,
        alias="category",
        description='Top-level ISMR occurrence category. Closed vocabulary per synth-rules table 7. Source CSV header "Category".\n',
    )
type: str = Field(
        ...,
        alias="type",
        description='ISMR occurrence type within the category (e.g. "Critical occurrences", "ODD exceedances", "Cybersecurity issues"). Closed vocabulary of 19 values per synth-rules table 7; (category, type) pair preserved verbatim. Source CSV header "Type".\n',
    )
count: int = Field(
        ...,
        alias="count",
        description='Number of occurrences of this (category, type) in the reporting period. Realistic range 0–25. Source CSV header "Count".\n',
    )
period: str = Field(
        ...,
        alias="period",
        description='Reporting period the count covers. Source CSV header "Period".\n',
    )
notes: Optional[str] = Field(
        None,
        alias="notes",
        description='Free-text notes from the operator. CARRIES HERO IDS — preserved verbatim from source and never regenerated by synthesis (see synth-rules table 7 invariants). Source CSV header "Notes".\n',
    )
ingested_at_utc: datetime = Field(
        ...,
        alias="_ingested_at_utc",
        description='Audit column — UTC timestamp when the row landed in Bronze.',
    )
source_file: Optional[str] = Field(
        None,
        alias="_source_file",
        description='Audit column — source CSV filename or URI.',
    )
correlation_id: str = Field(
        ...,
        alias="_correlation_id",
        description='Audit column — UUID linking the row to the upload batch.',
    )
dq_status: str = Field(
        ...,
        alias="_dq_status",
        description='Audit column — DQ Gate verdict set by internal data lineage.',
    )
source_lane: str = Field(
        ...,
        alias="_source_lane",
        description='Audit column — internal ingest lane that delivered this row.',
    )
raw_blob_path: str = Field(
        ...,
        alias="_raw_blob_path",
        description='Audit column — full ABFSS / S3 / queue URI of the raw payload as it landed in the source landing zone. Used for forensic replay and Purview lineage back to the raw blob. Supersedes the older _source_file audit column (kept for backward compatibility with ADR-002 v1 consumers); new ingest notebooks MUST set both to the same value when the source is file-shaped.\n',
    )
contract_version: str = Field(
        ...,
        alias="_contract_version",
        description='Audit column — semver of the Bronze ODCS contract under which this row was written (matches metadata.version). Lets Silver and the DQ Gate detect contract drift without re-reading the YAML.\n',
    )

